# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --network-timeout 1000000 --ignore-engines
COPY . .
RUN npm build
RUN npx http-server -p 5500 ./html
RUN npm run watch
# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]